create schema SNOWFLAKE_LEARNING_DB.DATA_GOVERNANACE;

create TABLE SNOWFLAKE_LEARNING_DB.DATA_GOVERNANACE.T_DESCRIPTION_DETAILS (
	AUDIT_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	DATABASE_NAME VARCHAR(50) ,
	SCHEMA_NAME VARCHAR(50),
	TABLE_NAME VARCHAR(100) ,
	RUN_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(20) ,
	TABLE_DESC VARCHAR(16777216) ,
	COLUMN_DESC VARIANT,
	ERROR_MESSAGE VARCHAR(1000)
);

CREATE TABLE SNOWFLAKE_LEARNING_DB.DATA_GOVERNANACE.T_DESCRIPTION_APPLY_AUDIT (
	LOG_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	DATABASE_NAME VARCHAR(50),
	SCHEMA_NAME VARCHAR(50),
	TABLE_NAME VARCHAR(100),
	COLUMN_NAME VARCHAR(100),
	DESCRIPTION VARCHAR,
	ACTION_TYPE VARCHAR(20), // TABLE_DESC or COLUMN_DESC
	APPLY_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP() ,
	STATUS VARCHAR(20),
	ERROR_MESSAGE VARCHAR(1000)
);
